/*
  # Bible Reading Schedule Application Schema

  ## Overview
  This migration creates the database structure for managing Bible reading schedules
  for group members with automatic rotation and assignment.

  ## New Tables

  ### `members`
  Stores information about group members who participate in Bible reading
  - `id` (uuid, primary key) - Unique identifier for each member
  - `name` (text) - Member's full name
  - `order_index` (integer) - Order position for rotation (0-based)
  - `created_at` (timestamptz) - Record creation timestamp
  - `is_active` (boolean) - Whether member is currently active in rotation

  ### `schedules`
  Stores generated reading schedules with book and chapter assignments
  - `id` (uuid, primary key) - Unique identifier for each schedule entry
  - `member_id` (uuid, foreign key) - References members table
  - `date` (date) - Date of the reading assignment
  - `book_name` (text) - Name of Bible book (e.g., "열왕기상")
  - `chapter` (integer) - Chapter number
  - `created_at` (timestamptz) - Record creation timestamp

  ### `config`
  Stores application configuration settings
  - `id` (uuid, primary key) - Unique identifier
  - `key` (text, unique) - Configuration key name
  - `value` (jsonb) - Configuration value (flexible JSON structure)
  - `updated_at` (timestamptz) - Last update timestamp

  ## Security
  - Enable RLS on all tables
  - Public access policies for demo purposes (can be restricted later)

  ## Notes
  1. Members are ordered by `order_index` for rotation scheduling
  2. Schedules can be regenerated by clearing and recalculating
  3. Config stores settings like chapters per person, starting book/chapter
*/

CREATE TABLE IF NOT EXISTS members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  order_index integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id uuid REFERENCES members(id) ON DELETE CASCADE,
  date date NOT NULL,
  book_name text NOT NULL,
  chapter integer NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  value jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to members"
  ON members FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert to members"
  ON members FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public update to members"
  ON members FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public delete from members"
  ON members FOR DELETE
  TO public
  USING (true);

CREATE POLICY "Allow public read access to schedules"
  ON schedules FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert to schedules"
  ON schedules FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public update to schedules"
  ON schedules FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public delete from schedules"
  ON schedules FOR DELETE
  TO public
  USING (true);

CREATE POLICY "Allow public read access to config"
  ON config FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert to config"
  ON config FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public update to config"
  ON config FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public delete from config"
  ON config FOR DELETE
  TO public
  USING (true);

CREATE INDEX IF NOT EXISTS idx_members_order ON members(order_index);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(date);
CREATE INDEX IF NOT EXISTS idx_config_key ON config(key);